services:
  - type: web
    name: fastapi-backend
    env: docker
    plan: starter
    dockerContext: signalExtractionApp/backend
    dockerfilePath: signalExtractionApp/backend/Dockerfile
    autoDeploy: true
